version: 0.2
phases:
  # install:
  #   commands:
  pre-build:
    commands:
      - 'npm install -g aws-cdk'
  build:
    commands:
      - 'mvn package -f ./src/pom.xml'
      - 'cdk synth'

artifacts:
  base-directory: 'cdk.out'
  files: '**/*'
  