version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  build:
    commands:
      - cd src
      - dotnet build -c Release
      - dotnet test -c Release --logger trx --results-directory ./testresults

reports:
  AppTestResults:
    file-format: VisualStudioTrx
    files:
      - '**/*'
    base-directory: './src/testresults'
