Resources:
  ProjectsLambdaServiceRole639DF816:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: WebsiteStack/ProjectsLambda/ServiceRole/Resource
  ProjectsLambdaServiceRoleDefaultPolicy27965771:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - projectstable524E346F
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: ProjectsLambdaServiceRoleDefaultPolicy27965771
      Roles:
        - Ref: ProjectsLambdaServiceRole639DF816
    Metadata:
      aws:cdk:path: WebsiteStack/ProjectsLambda/ServiceRole/DefaultPolicy/Resource
  ProjectsLambda25AA608C:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 5ab6ce7d40440f3e504db53432459adda8590a0078419e2835170b7674cfc81f.zip
      Handler: projects.handler
      Role:
        Fn::GetAtt:
          - ProjectsLambdaServiceRole639DF816
          - Arn
      Runtime: python3.8
    DependsOn:
      - ProjectsLambdaServiceRoleDefaultPolicy27965771
      - ProjectsLambdaServiceRole639DF816
    Metadata:
      aws:cdk:path: WebsiteStack/ProjectsLambda/Resource
      aws:asset:path: C:\Users\Evan\Documents\.repos\website-backend\src
      aws:asset:property: Code
  projectstable524E346F:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: false
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: WebsiteStack/projects-table/Resource
  Certificate4E7ABB08:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: ""
      DomainValidationOptions:
        - DomainName: ""
          HostedZoneId: Z2YUIRANSY13TZ
      ValidationMethod: DNS
    Metadata:
      aws:cdk:path: WebsiteStack/Certificate/Resource
  RestApi0C43BF4B:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: RestApi
    Metadata:
      aws:cdk:path: WebsiteStack/RestApi/Resource
  RestApiCloudWatchRoleE3ED6605:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: WebsiteStack/RestApi/CloudWatchRole/Resource
  RestApiAccount7C83CF5A:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - RestApiCloudWatchRoleE3ED6605
          - Arn
    DependsOn:
      - RestApi0C43BF4B
    Metadata:
      aws:cdk:path: WebsiteStack/RestApi/Account
  RestApiDeployment180EC503afbd7b5dc79b1311f1323802edb19877:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: RestApi0C43BF4B
      Description: Automatically created by the RestApi construct
    DependsOn:
      - RestApiprojectsGET1F0185EE
      - RestApiprojects886D5FB4
    Metadata:
      aws:cdk:path: WebsiteStack/RestApi/Deployment/Resource
  RestApiDeploymentStageprod3855DE66:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: RestApi0C43BF4B
      DeploymentId:
        Ref: RestApiDeployment180EC503afbd7b5dc79b1311f1323802edb19877
      StageName: prod
    Metadata:
      aws:cdk:path: WebsiteStack/RestApi/DeploymentStage.prod/Resource
  RestApiCustomDomain91FA5E60:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: ""
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn:
        Ref: Certificate4E7ABB08
      SecurityPolicy: TLS_1_2
    Metadata:
      aws:cdk:path: WebsiteStack/RestApi/CustomDomain/Resource
  RestApiCustomDomainMapWebsiteStackRestApi2E47B6F2D9597161:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName:
        Ref: RestApiCustomDomain91FA5E60
      RestApiId:
        Ref: RestApi0C43BF4B
      Stage:
        Ref: RestApiDeploymentStageprod3855DE66
    Metadata:
      aws:cdk:path: WebsiteStack/RestApi/CustomDomain/Map:--=>WebsiteStackRestApi2E47B6F2/Resource
  RestApiprojects886D5FB4:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - RestApi0C43BF4B
          - RootResourceId
      PathPart: projects
      RestApiId:
        Ref: RestApi0C43BF4B
    Metadata:
      aws:cdk:path: WebsiteStack/RestApi/Default/projects/Resource
  RestApiprojectsGETApiPermissionWebsiteStackRestApi2E47B6F2GETprojectsD32DD8E9:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - ProjectsLambda25AA608C
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: RestApi0C43BF4B
            - /
            - Ref: RestApiDeploymentStageprod3855DE66
            - /GET/projects
    Metadata:
      aws:cdk:path: WebsiteStack/RestApi/Default/projects/GET/ApiPermission.WebsiteStackRestApi2E47B6F2.GET..projects
  RestApiprojectsGETApiPermissionTestWebsiteStackRestApi2E47B6F2GETprojects5ADBB5C5:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - ProjectsLambda25AA608C
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: RestApi0C43BF4B
            - /test-invoke-stage/GET/projects
    Metadata:
      aws:cdk:path: WebsiteStack/RestApi/Default/projects/GET/ApiPermission.Test.WebsiteStackRestApi2E47B6F2.GET..projects
  RestApiprojectsGET1F0185EE:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: RestApiprojects886D5FB4
      RestApiId:
        Ref: RestApi0C43BF4B
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - ProjectsLambda25AA608C
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: WebsiteStack/RestApi/Default/projects/GET/Resource
  ARecordE7B57761:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: evanparizot.com.
      Type: A
      AliasTarget:
        DNSName:
          Fn::GetAtt:
            - RestApiCustomDomain91FA5E60
            - RegionalDomainName
        HostedZoneId:
          Fn::GetAtt:
            - RestApiCustomDomain91FA5E60
            - RegionalHostedZoneId
      HostedZoneId: Z2YUIRANSY13TZ
    Metadata:
      aws:cdk:path: WebsiteStack/ARecord/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.70.0,@aws-cdk/assets=1.71.0,@aws-cdk/aws-apigateway=1.71.0,@aws-cdk/aws-applicationautoscaling=1.71.0,@aws-cdk/aws-autoscaling=1.71.0,@aws-cdk/aws-autoscaling-common=1.71.0,@aws-cdk/aws-autoscaling-hooktargets=1.71.0,@aws-cdk/aws-certificatemanager=1.71.0,@aws-cdk/aws-cloudformation=1.71.0,@aws-cdk/aws-cloudwatch=1.71.0,@aws-cdk/aws-codebuild=1.71.0,@aws-cdk/aws-codeguruprofiler=1.71.0,@aws-cdk/aws-codepipeline=1.71.0,@aws-cdk/aws-codepipeline-actions=1.71.0,@aws-cdk/aws-dynamodb=1.71.0,@aws-cdk/aws-ec2=1.71.0,@aws-cdk/aws-ecr=1.71.0,@aws-cdk/aws-ecr-assets=1.71.0,@aws-cdk/aws-ecs=1.71.0,@aws-cdk/aws-elasticloadbalancingv2=1.71.0,@aws-cdk/aws-events=1.71.0,@aws-cdk/aws-events-targets=1.71.0,@aws-cdk/aws-iam=1.71.0,@aws-cdk/aws-kms=1.71.0,@aws-cdk/aws-lambda=1.71.0,@aws-cdk/aws-logs=1.71.0,@aws-cdk/aws-route53=1.71.0,@aws-cdk/aws-route53-targets=1.71.0,@aws-cdk/aws-s3=1.71.0,@aws-cdk/aws-s3-assets=1.71.0,@aws-cdk/aws-servicediscovery=1.71.0,@aws-cdk/aws-sns=1.71.0,@aws-cdk/aws-sns-subscriptions=1.71.0,@aws-cdk/aws-sqs=1.71.0,@aws-cdk/aws-ssm=1.71.0,@aws-cdk/cloud-assembly-schema=1.71.0,@aws-cdk/core=1.71.0,@aws-cdk/custom-resources=1.71.0,@aws-cdk/cx-api=1.71.0,@aws-cdk/pipelines=1.71.0,@aws-cdk/region-info=1.71.0,jsii-runtime=node.js/v14.15.0
    Metadata:
      aws:cdk:path: WebsiteStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  RestApiEndpoint0551178A:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: RestApi0C43BF4B
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: RestApiDeploymentStageprod3855DE66
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store.
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 4 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

